on:
  workflow_dispatch:
    inputs:
      tweet:
        description: 'Enter your Tweet'
        required: true
        default: ''  

jobs:
  tweetsh_action:
    runs-on: ubuntu-latest
    name: Run tweet.sh
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: make entrypoint script executable
        run: |
          chmod +x src/entrypoint.sh
      - name: Run tweet.sh
        uses: ./ # Uses an action in the root directory
        with:
          command: |
            ${{ github.event.inputs.tweet }}